version: '2'
services:
    calendarioapp-app:
        image: calendarioapp
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mariadb://calendarioapp-mariadb:3306/calendarioapp
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    calendarioapp-mariadb:
        extends:
            file: mariadb.yml
            service: calendarioapp-mariadb
